spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
            - Method=GET,POST
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/orderFallback
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: paymentServiceCircuitBreaker
                fallbackUri: forward:/paymentFallback
        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/auth/**
  config:
    import: configserver:http://localhost:9196
server:
  port: 8989

resilience4j.retry:
  configs:
    default:
      max-attempts: 3
      waitDuration: 100s

